/**
 * Medicare / Medicaid graduate-medical-education (GME) funding calculations.
 *
 * Two Medicare streams matter for a new residency program:
 *
 *   1. Direct GME (DGME) — reimburses direct training costs (resident stipends,
 *      supervising-physician time, overhead). Paid as:
 *          DGME = PRA x weightedResidentFTE x MedicareInpatientShare
 *      where PRA is the hospital's Per-Resident Amount.
 *
 *   2. Indirect Medical Education (IME) — an add-on percentage applied to
 *      Medicare inpatient PPS operating payments to reflect the higher costs of
 *      teaching hospitals:
 *          IME% = c x [ (1 + r)^0.405 - 1 ],  c = 1.35
 *      where r = residentFTE / availableBeds. IME is NONLINEAR in r, so the
 *      marginal value of new residents is computed as the difference between
 *      IME dollars with and without the new residents.
 *
 * BOTH streams are subject to the hospital's resident FTE cap (set from a
 * historical base year). FTEs above the cap generate no additional Medicare
 * DGME or IME. We honor the cap by only counting fundable FTEs.
 *
 * Medicaid GME is state-specific and modeled as a flat per-resident amount.
 */

import { IME_EXPONENT, IME_MULTIPLIER, DGME_FTE_WEIGHT } from "./constants";
import type { GmeFundingInputs } from "./types";

/**
 * Number of new resident FTEs that actually fall under the Medicare cap and so
 * are eligible to generate DGME/IME revenue.
 */
export function fundableFte(totalNewFte: number, gme: GmeFundingInputs): number {
  // "At cap" means the hospital's resident count already meets its Medicare
  // FTE cap, so new residents generate no additional funded FTE. A hospital
  // with partial room should instead leave this off and set capHeadroomFte.
  if (gme.atMedicareCap) return 0;
  // Under cap: fundable up to the remaining headroom.
  return clampNonNeg(Math.min(totalNewFte, gme.capHeadroomFte));
}

/** Annual Direct GME revenue generated by the fundable resident FTEs. */
export function directGme(totalNewFte: number, gme: GmeFundingInputs): number {
  const fte = fundableFte(totalNewFte, gme);
  return (
    gme.directGmePerResidentAmount *
    DGME_FTE_WEIGHT *
    fte *
    clamp01(gme.medicareInpatientShare)
  );
}

/** The IME operating add-on percentage for a given resident-to-bed ratio. */
export function imePercentage(residentFte: number, availableBeds: number): number {
  if (availableBeds <= 0) return 0;
  const r = residentFte / availableBeds;
  return IME_MULTIPLIER * (Math.pow(1 + r, IME_EXPONENT) - 1);
}

/**
 * Marginal annual IME revenue attributable to the new anesthesia residents.
 * Computed as IME(existing + fundableNew) - IME(existing), because IME is
 * nonlinear in the resident-to-bed ratio.
 */
export function marginalIme(totalNewFte: number, gme: GmeFundingInputs): number {
  const fundableNew = fundableFte(totalNewFte, gme);
  const base = gme.existingResidentFte;
  const withNew = base + fundableNew;
  const pctBase = imePercentage(base, gme.availableBeds);
  const pctWith = imePercentage(withNew, gme.availableBeds);
  const deltaPct = pctWith - pctBase;
  return gme.medicareInpatientOperatingPayments * deltaPct;
}

/** State Medicaid GME support for all resident FTEs (not subject to Medicare cap). */
export function medicaidGme(totalFte: number, gme: GmeFundingInputs): number {
  return gme.medicaidGmePerResident * clampNonNeg(totalFte);
}

function clamp01(x: number): number {
  return Math.max(0, Math.min(1, x));
}

function clampNonNeg(x: number): number {
  return Math.max(0, x);
}
